### 列表操作
GET /Discussions/Forums?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 模式查询
GET /Discussions/Forums/Visibility:all+CreatedTime:thisyear?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 查询操作
# 注：有关查询条件请参考对应的条件实体类的定义。
POST /Discussions/Forums/Query?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

{
	"Name": "%",
	"IsPopular": true,
	"TotalThreads": "0~9999999",
	"CreatedTime": "thisyear()"
}

### 编号查询
@id = {{$input 论坛编号 $value:100 }}
GET /Discussions/Forums/{{id}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 创建操作
@name = {{$input 论坛名称 $value: }}
POST /Discussions/Forums HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

{
	"Name": "{{name}}"
}

### 更新操作
@id = {{$input 论坛编号 $value: }}
@field = {{$input 字段名称 $value: }}
@value = {{$input 字段内容 $value: }}
PATCH /Discussions/Forums/{{id}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

{
	"{{field}}": "{{value}}"
}

### 删除操作
@id = {{$input 论坛编号 $value:404 }}
DELETE /Discussions/Forums/{{id}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 批量删除
DELETE /Discussions/Forums HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: text/plain

401,402,403

### 导出操作
GET /Discussions/Forums/Export?format=spreadsheet HTTP/1.1
Host: {{host}}:{{port}}
X-Data-Schema: *
X-Export-Fields: *
Authorization: Credential {{credentialId}}
