### 列表操作
@id = {{$input 论坛编号 $value:100 }}
GET /Discussions/Forums/{{id}}/Users?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 新增操作
@forumId = {{$input 论坛编号 $value:100 }}
@userId = {{$input 用户编号 $value:100 }}
POST /Discussions/Forums/{{forumId}}/Users HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

[
	{
		"UserId": {{userId}},
		"Permission": "All"
	}
]

### 增改操作
@forumId = {{$input 论坛编号 $value:100 }}
@userId = {{$input 用户编号 $value:100 }}
PUT /Discussions/Forums/{{forumId}}/Users HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

[
	{
		"UserId": {{userId}},
		"Permission": "All"
	}
]

### 更新操作
@forumId = {{$input 论坛编号 $value:100 }}
@userId = {{$input 用户编号 $value:100 }}
PATCH /Discussions/Forums/{{forumId}}/Users HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

[
	{
		"UserId": {{userId}},
		"Permission": "All"
	}
]

### 删除操作
@forumId = {{$input 论坛编号 $value:404 }}
@userId = {{$input 用户编号 $value:1 }}
DELETE /Discussions/Forums/Users/{{forumId}}-{{userId}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 批量删除
DELETE /Discussions/Forums/Users HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

404-1,404-2,404-3

### 清空操作
@id = {{$input 论坛编号 $value:404 }}
DELETE /Discussions/Forums/{{id}}/Users HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
