### 列表操作
GET /Discussions/Sites?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 编号查询
@id = {{$input 站点编号 $value:100 }}
GET /Discussions/Sites/{{id}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 模式查询
GET /Discussions/Sites/name:MySite+host:localhost?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 查询操作
# 注：有关查询条件请参考对应的条件实体类的定义。
POST /Discussions/Sites/Query?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

{
	"Name": "%",
	"Host": "localhost",
	"Domain": "_"
}

### 创建操作
@name = {{$input 站点名称 $value: }}
@domain = {{$input 域名 $value: }}
POST /Discussions/Sites HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

{
	"Name": "{{name}}",
	"Host": "{{host}}",
	"Domain": "{{domain}}"
}

### 更新操作
@id = {{$input 站点编号 $value: }}
@field = {{$input 字段名称 $value: }}
@value = {{$input 字段内容 $value: }}
PATCH /Discussions/Sites/{{id}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

{
	"{{field}}": "{{value}}"
}

### 删除操作
@id = {{$input 站点编号 $value:404 }}
DELETE /Discussions/Sites/{{id}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 批量删除
DELETE /Discussions/Sites HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: text/plain

401,402,403

### 导出操作
GET /Discussions/Sites/Export?format=spreadsheet HTTP/1.1
Host: {{host}}:{{port}}
X-Data-Schema: *
X-Export-Fields: *
Authorization: Credential {{credentialId}}
