### 列表操作
GET /Discussions/Threads?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 模式查询
GET /Discussions/Threads/IsLocked:false+IsValued:true+CreatedTime:thisyear?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 查询操作
# 注：有关查询条件请参考对应的条件实体类的定义。
POST /Discussions/Threads/Query?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

{
	"Approved": true,
	"IsLocked": false,
	"TotalReplies": "0~999999",
	"CreatedTime": "thisyear()"
}

### 编号查询
@id = {{$input 主题编号 $value:100 }}
GET /Discussions/Threads/{{id}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 创建操作
@title = {{$input 主题标题 $value: }}
@summary = {{$input 主题摘要 $value: }}
@siteId = {{$input 站点编号 $value:100003 }}
@forumId = {{$input 论坛编号 $value: }}
@content = {{$input 主题正文 $value: }}
POST /Discussions/Threads HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

{
	"SiteId": {{siteId}},
	"ForumId": {{forumId}},
	"Title": "{{title}}",
	"Summary": "{{summary}}",
	"Post": {
		"Content": "{{content}}",
		"ContentType": "text/plain+embedded"
	}
}

### 更新操作
@id = {{$input 主题编号 $value: }}
@field = {{$input 字段名称 $value: }}
@value = {{$input 字段内容 $value: }}
PATCH /Discussions/Threads/{{id}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

{
	"{{field}}": "{{value}}"
}

### 删除操作
@id = {{$input 主题编号 $value:404 }}
DELETE /Discussions/Threads/{{id}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 批量删除
DELETE /Discussions/Threads HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: text/plain

401,402,403

### 导出操作
GET /Discussions/Threads/Export?format=spreadsheet HTTP/1.1
Host: {{host}}:{{port}}
X-Data-Schema: *
X-Export-Fields: *
Authorization: Credential {{credentialId}}

### 审批主题
POST /Discussions/Threads/{{id}}/Approve HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 隐藏主题
POST /Discussions/Threads/{{id}}/Hidden HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 显示主题
POST /Discussions/Threads/{{id}}/Visible HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 锁定主题
POST /Discussions/Threads/{{id}}/Lock HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 解锁主题
POST /Discussions/Threads/{{id}}/Unlock HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 置顶主题
POST /Discussions/Threads/{{id}}/Pin HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 取消置顶
POST /Discussions/Threads/{{id}}/Unpin HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 加精主题
POST /Discussions/Threads/{{id}}/Valued HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 取消加精
POST /Discussions/Threads/{{id}}/Unvalued HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 全局主题
POST /Discussions/Threads/{{id}}/Global HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 取消全局
POST /Discussions/Threads/{{id}}/Unglobal HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 记录总数
GET /Discussions/Threads/Count HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 判断记录是否存在
@existsKey = {{$input 记录编号 $value:10000006 }}
GET /Discussions/Threads/{{existsKey}}/Exists HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
